rmdir /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache"
del /f /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache"
rmdir /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\logs"
del /f /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\logs"
rmdir /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames"
del /f /s /q "%systemdrive%\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames"
rmdir /s /q "%systemdrive%\Users\%USERNAME%\AppData\Local\Ubisoft Game Launcher\spool"
rmdir /s /q "%systemdrive%\Users\%USERNAME%\AppData\Local\Temp"
del /f /s /q "%systemdrive%\Windows\Prefetch"
del /f /s /q "%systemdrive%\Windows\Temp"